### ISSUE TITLE
Does not work with current verison of kaptive

### ISSUE THREAD

**Issue by erinyoung** [aldertzomer/vibrio_parahaemolyticus_genomoserotyping#3]
I was updating kaptive to version 3.0.0b1, and noticed that this version doesn't appear to work with these gbk files anymore.

What I ran:
```
wget -q https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/558/495/GCF_001558495.2_ASM155849v2/GCF_001558495.2_ASM155849v2_genomic.fna.gz
wget -q https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/728/135/GCF_001728135.1_ASM172813v1/GCF_001728135.1_ASM172813v1_genomic.fna.gz
gzip -d GCF_001558495.2_ASM155849v2_genomic.fna.gz
gzip -d GCF_001728135.1_ASM172813v1_genomic.fna.gz
kaptive assembly VibrioPara_Kaptivedb_K.gbk *.fna -o /test3/Vparahaemolyticus 
```
  
The error I observed:
```
Traceback (most recent call last):
   File "/usr/local/bin/kaptive", line 8, in <module>
     sys.exit(main())
   File "/usr/local/lib/python3.9/site-packages/kaptive/__main__.py", line 293, in main
     if (result := typing_pipeline(
   File "/usr/local/lib/python3.9/site-packages/kaptive/assembly.py", line 163, in typing_pipeline
     for_scoring = [(
   File "/usr/local/lib/python3.9/site-packages/kaptive/assembly.py", line 164, in <listcomp>
     db.loci[locus], list(a)) for locus, a in groupby(  # Group alignments by locus
 KeyError: 'KL155-1'
```
  
  Are you going to be updating your files?

**Comment by aldertzomer** [comment]
@tomdstanton I think the Kaptive database format has changed for Kaptive3.  Can you tell use the necessary changes to make it work again?

**Comment by tomdstanton** [comment]
Hi both,
This shouldn't be due to the v3 update, but I think is due to the issue flagged in #1.
See my fix in PR #4

**Comment by aldertzomer** [comment]
ah I missed the fix. I just uploaded a fixed version with KL155-1 instead of KL1155-1

**Comment by indexofire** [comment]
kaptive v3b4/v3b5 work fine with the vp database on my server.

**Comment by erinyoung** [comment]
I forgot I let this issue remain open. My apologies! The current version (3.0.0b6) of kaptive works great with these files.
